AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - preprod
      - prod
    Description: The environment to deploy (e.g., prod)
  ApiDomain:
    Type: String
    Description: Root domain for the API (e.g., domain.com)

Mappings:
  EnvironmentConfig:
    dev:
      Environment: dev
      PublicApiUrlSubDomainSuffix: dev-jobs-rest-api
    preprod:
      Environment: preprod
      PublicApiUrlSubDomainSuffix: preprod-jobs-rest-api
    prod:
      Environment: prod
      PublicApiUrlSubDomainSuffix: jobs-rest-api

Resources:
  FastApiLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: FastApiDependencies
      ContentUri: layers/fastapi
      CompatibleRuntimes:
        - python3.13
    Metadata:
      BuildMethod: python3.13

  ProdUsagePlan:
    Type: 'AWS::ApiGateway::UsagePlan'
    Properties:
      Quota:
        Limit: 100
        Period: DAY
      Throttle:
        BurstLimit: 1
        RateLimit: 1
      UsagePlanName: ProdUsagePlan

  ServerlessApiGW:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Environment
      EndpointConfiguration:
        Type: REGIONAL
      MethodSettings:
        - ResourcePath: "/*"
          HttpMethod: "*"
          ThrottlingBurstLimit: 1
          ThrottlingRateLimit: 1
      Domain:
        DomainName: !Sub
            - "${PublicApiUrlSubDomainSuffix}.${ApiDomain}"
            - {
                PublicApiUrlSubDomainSuffix: !FindInMap [EnvironmentConfig, !Ref Environment, PublicApiUrlSubDomainSuffix],
                ApiDomain: !Ref ApiDomain
            }
        CertificateArn: '{{resolve:secretsmanager:examples/sam_api:SecretString:SSL_CERTIFICATE_ARN}}'
        Route53:
          HostedZoneId: '{{resolve:secretsmanager:examples/sam_api:SecretString:HOSTED_ZONE_ID}}'

  JobsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.main.handler
      Runtime: python3.13
      CodeUri: ./
      MemorySize: 128
      Timeout: 5
      Policies:
        - DynamoDBCrudPolicy:
            TableName: '{{resolve:secretsmanager:examples/sam_api:SecretString:DYNAMO_DB_TABLE}}'
      Layers:
        - !Ref FastApiLayer
      Events:
        ExampleProjectInfoEndpoint:
          Type: Api
          Properties:
            RestApiId: !Ref ServerlessApiGW
            Path: /v1/info/
            Method: GET
        GetJobApiEndpoint:
          Type: Api
          Properties:
            RestApiId: !Ref ServerlessApiGW
            Path: /v1/jobs/{company}/{timestamp}/
            Method: GET
        ListJobsApiEndpoint:
          Type: Api
          Properties:
            RestApiId: !Ref ServerlessApiGW
            Path: /v1/jobs/
            Method: GET
        CreateJobApiEndpoint:
          Type: Api
          Properties:
            RestApiId: !Ref ServerlessApiGW
            Path: /v1/jobs/
            Method: POST
        UpdateJobApiEndpoint:
          Type: Api
          Properties:
            RestApiId: !Ref ServerlessApiGW
            Path: /v1/jobs/{company}/{timestamp}/
            Method: PATCH
        DeleteJobApiEndpoint:
          Type: Api
          Properties:
            RestApiId: !Ref ServerlessApiGW
            Path: /v1/jobs/{company}/{timestamp}/
            Method: DELETE
      Environment:
        Variables:
          APP_ENV: !Ref Environment
          APP_STACK_NAME : !Ref AWS::StackName
          JOBS_TABLE_NAME: '{{resolve:secretsmanager:examples/sam_api:SecretString:DYNAMO_DB_TABLE}}'

  SwaggerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.main.handler
      Runtime: python3.13
      CodeUri: ./
      MemorySize: 128
      Timeout: 5
      Layers:
        - !Ref FastApiLayer
      Events:
        SwaggerApi:
          Type: Api
          Properties:
            RestApiId: !Ref ServerlessApiGW
            Path: /docs
            Method: GET
        RedocApi:
          Type: Api
          Properties:
            RestApiId: !Ref ServerlessApiGW
            Path: /redoc
            Method: GET
        OpenAPI:
          Type: Api
          Properties:
            RestApiId: !Ref ServerlessApiGW
            Path: /openapi.json
            Method: GET
      Environment:
        Variables:
          APP_ENV: !Ref Environment

  JobsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: '{{resolve:secretsmanager:examples/sam_api:SecretString:DYNAMO_DB_TABLE}}'
      AttributeDefinitions:
        - AttributeName: company
          AttributeType: S
        - AttributeName: time_stamp
          AttributeType: S
      KeySchema:
        - AttributeName: company
          KeyType: HASH
        - AttributeName: time_stamp
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  AlertTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "${AWS::StackName}-alerts"
      DisplayName: Jobs API Alerts
      Subscription:
        - Endpoint: '{{resolve:secretsmanager:examples/sam_api:SecretString:ADMIN_EMAIL}}'
          Protocol: email

  GatewayAPIThrottleAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "${AWS::StackName}-apigw-throttle"
      AlarmDescription: Alert when API Gateway requests are throttled (HTTP 429)
      MetricName: 4XXError
      Namespace: AWS/ApiGateway
      Statistic: Sum
      Period: 60
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: ApiName
          Value: !Ref AWS::StackName
      TreatMissingData: notBreaching
      AlarmActions:
        - !Ref AlertTopic

Outputs:
  AlertTopicArn:
    Description: ARN of SNS topic for alerts
    Value: !Ref AlertTopic
    Export:
      Name: !Sub "${AWS::StackName}-AlertTopic"